commerce:
    resource: "@CommerceBundle/Resources/config/routing.yml"
    prefix:   /

categories:
    type:     rest
    resource: CommerceBundle\Controller\CategoriesController

produits:
    type:     rest
    resource: CommerceBundle\Controller\ProduitsController
